ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM registry.cn-hongkong.aliyuncs.com/booster/elastic:k_${ELASTIC_VERSION:-8.17.0}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
