services:
  enterprise-search:
    build:
      context: extensions/enterprise-search/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    hostname: enterprise-search
    image: docker_elk_enterprise-search:${ELASTIC_VERSION}
    volumes:
      - ./extensions/enterprise-search/config/enterprise-search.yml:/usr/share/enterprise-search/config/enterprise-search.yml:ro,Z
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx2g"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-}
      - ENT_SEARCH_DEFAULT_PASSWORD='changeme'
      - ENT_SEARCH_SKIP_KIBANA_AVAILABILITY_CHECK=true
    ports:
      - "3002:3002"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana