ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM registry.cn-hongkong.aliyuncs.com/booster/elastic:e_${ELASTIC_VERSION:-8.17.0}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
