ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM registry.cn-hongkong.aliyuncs.com/booster/elastic:l_${ELASTIC_VERSION:-8.17.0}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
